-- SKANEXA V.12.1 -> Supabase PostgreSQL
-- Generated from database/schema.sql + dynamic schemas in the uploaded project.
-- Run in Supabase SQL Editor on a NEW/EMPTY project.

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  normalized_name VARCHAR(100) NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  normalized_name VARCHAR(150) NOT NULL,
  class_id BIGINT NOT NULL REFERENCES classes(id) ON DELETE RESTRICT,
  photo_path VARCHAR(500),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  has_voted SMALLINT NOT NULL DEFAULT 0 CHECK (has_voted IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (normalized_name, class_id)
);
CREATE INDEX IF NOT EXISTS idx_participants_class ON participants(class_id);

CREATE TABLE IF NOT EXISTS polls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  description TEXT,
  poll_type TEXT NOT NULL DEFAULT 'single_choice' CHECK (poll_type IN ('single_choice','multiple_choice','yes_no','image_choice','questionnaire')),
  access_mode TEXT NOT NULL DEFAULT 'token_verification' CHECK (access_mode IN ('token_verification','verification_only','token_only')),
  token_hash CHAR(64),
  token_rotated_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','scheduled','active','paused','closed','archived','inactive')),
  start_at TIMESTAMPTZ,
  end_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  image_url VARCHAR(255),
  description TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_candidates_poll ON candidates(poll_id);

CREATE TABLE IF NOT EXISTS poll_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL UNIQUE REFERENCES polls(id) ON DELETE CASCADE,
  min_choices INT NOT NULL DEFAULT 1,
  max_choices INT NOT NULL DEFAULT 1,
  allow_change_vote SMALLINT NOT NULL DEFAULT 0 CHECK (allow_change_vote IN (0,1)),
  show_results SMALLINT NOT NULL DEFAULT 0 CHECK (show_results IN (0,1)),
  randomize_candidates SMALLINT NOT NULL DEFAULT 0 CHECK (randomize_candidates IN (0,1)),
  max_questions INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS poll_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  question_text VARCHAR(500) NOT NULL,
  image_url VARCHAR(255),
  question_type TEXT NOT NULL DEFAULT 'single_choice' CHECK (question_type IN ('single_choice','multiple_choice','yes_no')),
  sort_order INT NOT NULL DEFAULT 0,
  required SMALLINT NOT NULL DEFAULT 1 CHECK (required IN (0,1)),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_poll_questions_poll ON poll_questions(poll_id);

CREATE TABLE IF NOT EXISTS poll_question_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES poll_questions(id) ON DELETE CASCADE,
  option_text VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  ends_poll SMALLINT NOT NULL DEFAULT 0 CHECK (ends_poll IN (0,1)),
  next_question_id BIGINT,
  target_poll_id BIGINT,
  image_url VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_pqo_question ON poll_question_options(question_id);
CREATE INDEX IF NOT EXISTS idx_pqo_next_question ON poll_question_options(next_question_id);
CREATE INDEX IF NOT EXISTS idx_pqo_target_poll ON poll_question_options(target_poll_id);

CREATE TABLE IF NOT EXISTS poll_participations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  participant_id BIGINT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  current_question_id BIGINT,
  status TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress','completed','terminated')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (poll_id, participant_id)
);
CREATE INDEX IF NOT EXISTS idx_ppart_poll ON poll_participations(poll_id);
CREATE INDEX IF NOT EXISTS idx_ppart_participant ON poll_participations(participant_id);
CREATE INDEX IF NOT EXISTS idx_ppart_current_question ON poll_participations(current_question_id);

CREATE TABLE IF NOT EXISTS poll_answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  participant_id BIGINT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  question_id BIGINT NOT NULL REFERENCES poll_questions(id) ON DELETE CASCADE,
  option_id BIGINT NOT NULL REFERENCES poll_question_options(id) ON DELETE CASCADE,
  is_draft SMALLINT NOT NULL DEFAULT 0 CHECK (is_draft IN (0,1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (poll_id, participant_id, question_id, option_id)
);
CREATE INDEX IF NOT EXISTS idx_answers_question ON poll_answers(question_id);
CREATE INDEX IF NOT EXISTS idx_answers_option ON poll_answers(option_id);

CREATE TABLE IF NOT EXISTS poll_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  participant_id BIGINT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (poll_id, participant_id)
);
CREATE INDEX IF NOT EXISTS idx_poll_participants_poll ON poll_participants(poll_id);
CREATE INDEX IF NOT EXISTS idx_poll_participants_participant ON poll_participants(participant_id);

CREATE TABLE IF NOT EXISTS votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
  participant_id BIGINT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  candidate_id BIGINT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  ip_hash VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (poll_id, participant_id)
);
CREATE INDEX IF NOT EXISTS idx_votes_poll_candidate ON votes(poll_id, candidate_id);
CREATE INDEX IF NOT EXISTS idx_votes_participant ON votes(participant_id);
CREATE INDEX IF NOT EXISTS idx_votes_candidate ON votes(candidate_id);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(50),
  entity_id BIGINT,
  description TEXT,
  ip_hash VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_admin ON audit_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);

-- NEXADIPTA 21 website schema
CREATE TABLE IF NOT EXISTS website_settings (
  setting_key VARCHAR(100) PRIMARY KEY,
  setting_value TEXT,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS website_timeline (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  description TEXT,
  event_date DATE,
  location VARCHAR(255),
  start_time TIME,
  end_time TIME,
  media_type TEXT NOT NULL DEFAULT 'none' CHECK (media_type IN ('none','image','video')),
  media_url VARCHAR(500),
  sort_order INT NOT NULL DEFAULT 0,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_timeline_active ON website_timeline(is_active, event_date, sort_order);

CREATE TABLE IF NOT EXISTS website_gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  description TEXT,
  image_path VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_gallery_active ON website_gallery(is_active, sort_order, id);

CREATE TABLE IF NOT EXISTS website_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label VARCHAR(120) NOT NULL,
  url VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_contacts_active ON website_contacts(is_active, sort_order, id);

-- Default NEXADIPTA 21 website settings from the PHP application.
INSERT INTO website_settings(setting_key, setting_value) VALUES
('site_name','NEXADIPTA 21'),
('tagline','The Story of Our Generation'),
('hero_title','The Story of Our Generation.'),
('hero_description','Satu angkatan, banyak cerita. Tempat untuk mengenang perjalanan, mengenal teman seperjalanan, dan ikut menentukan hal-hal penting lewat polling.'),
('year','2021'),
('about_title','Tentang NEXADIPTA 21'),
('about_text','Tempat untuk menyimpan cerita, jadwal, momen, dan kegiatan NEXADIPTA 21.'),
('hero_image',''),
('logo_image','')
ON CONFLICT (setting_key) DO NOTHING;

-- Updated_at triggers (PostgreSQL equivalent of MySQL ON UPDATE CURRENT_TIMESTAMP).
CREATE OR REPLACE FUNCTION skanexa_set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['admins','classes','participants','polls','candidates','poll_settings','poll_questions','poll_question_options','poll_participations','poll_participants','website_settings','website_timeline','website_gallery','website_contacts']
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I', t, t);
    EXECUTE format('CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION skanexa_set_updated_at()', t, t);
  END LOOP;
END $$;
