<?php
require_once __DIR__ . '/../includes/functions.php';
$pdo = get_db();
require_once __DIR__.'/includes/content.php';
ensure_nexadipta21_schema($pdo);
$siteName=nx21_setting($pdo,'site_name','NEXADIPTA 21'); $tagline=nx21_setting($pdo,'tagline','The Story of Our Generation'); $heroTitle=nx21_setting($pdo,'hero_title','The Story of Our Generation.'); $heroDescription=nx21_setting($pdo,'hero_description','Satu angkatan, banyak cerita.'); $year=nx21_setting($pdo,'year','2021'); $heroImage=nx21_setting($pdo,'hero_image','');
$pageTitle='NEXADIPTA 21 — The Story of Our Generation'; $activePage='home';
$polls=$pdo->query("SELECT id,title,poll_type,status,description FROM polls WHERE status IN ('active','scheduled','paused') ORDER BY id DESC")->fetchAll();
$visibleResults=[];
foreach($polls as $p){ $s=get_poll_settings((int)$p['id']); if(!empty($s['show_results'])) $visibleResults[]=['poll'=>$p,'rows'=>$p['poll_type']==='questionnaire'?get_questionnaire_result_rows((int)$p['id']):get_public_poll_result_rows((int)$p['id'])]; }
include __DIR__.'/includes/header.php';
?>
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow"><?= e($siteName) ?></span><h1><?= e($heroTitle) ?></h1><p class="lead"><?= e($heroDescription) ?></p><div class="hero-actions"><a class="btn btn-primary" href="<?= nx21_url('polling.php') ?>">Ikuti Polling</a><a class="btn btn-ghost" href="<?= nx21_url('tentang.php') ?>">Tentang Angkatan</a></div><div class="hero-meta"><span>Memories</span><span>Friendship</span><span>One Generation</span></div></div><div class="hero-card"><?php if($heroImage): ?><img class="hero-photo" src="<?= e(nx21_media_url($heroImage)) ?>" alt="<?= e($siteName) ?>"><?php else: ?><div class="hero-photo-placeholder"><div><span class="photo-icon">N21</span><strong>Foto utama angkatan</strong><small>-</small></div></div><?php endif; ?><div class="hero-card-caption"><span>EST.</span><strong><?= e($year) ?></strong><span>•</span><span><?= e($siteName) ?></span></div></div></div></section>
<section class="stats-strip"><div class="container stats-grid"><div><strong><?= e($year) ?></strong><span>Tahun angkatan</span></div><div><strong>21</strong><span>Kenangan</span></div><div><strong><?= count($polls) ?></strong><span>Polling tersedia</span></div><div><strong><?= count($visibleResults) ?></strong><span>Hasil terbuka</span></div></div></section>
<section class="section"><div class="container section-head"><div><span class="section-kicker">HASIL POLLING</span><h2>Hasil yang sudah dibuka.</h2></div><p>Hasil polling yang diizinkan tampil publik bisa dilihat langsung di sini.</p></div><div class="results-preview">
<?php if(!$visibleResults): ?><div class="empty-card">Belum ada hasil polling..</div><?php else: foreach($visibleResults as $item): $p=$item['poll']; $rows=$item['rows']; if($p['poll_type']==='questionnaire'): ?><article class="result-card"><span class="poll-status">QUESTIONNAIRE</span><h3><?= e($p['title']) ?></h3><?php foreach(array_slice($rows,0,3) as $q): $qt=0; foreach($q['options'] as $o)$qt+=(int)$o['vote_count']; ?><div class="mini-question"><strong><?= e($q['question']) ?></strong><?php foreach($q['options'] as $o): $pct=$qt?round(((int)$o['vote_count']/$qt)*100,1):0; ?><div class="chart-row"><div class="chart-label"><?= e($o['option_text']) ?></div><div class="chart-track"><div class="chart-fill" style="width:<?= max($pct,$o['vote_count']>0?4:0) ?>%"><?= $pct ?>%</div></div><div class="chart-count"><?= (int)$o['vote_count'] ?></div></div><?php endforeach; ?></div><?php endforeach; ?><a class="btn btn-outline" href="<?= nx21_url('hasil.php') ?>">Lihat semua hasil →</a></article><?php else: $total=0; foreach($rows as $r)$total+=(int)$r['vote_count']; ?><article class="result-card"><span class="poll-status">HASIL POLLING</span><h3><?= e($p['title']) ?></h3><p class="result-total">Total vote: <strong><?= $total ?></strong></p><?php foreach(array_slice($rows,0,5) as $r): $pct=$total?round(((int)$r['vote_count']/$total)*100,1):0; ?><div class="chart-row"><div class="chart-label"><?= e($r['name']) ?></div><div class="chart-track"><div class="chart-fill" style="width:<?= max($pct,$r['vote_count']>0?4:0) ?>%"><?= $pct ?>%</div></div><div class="chart-count"><?= (int)$r['vote_count'] ?></div></div><?php endforeach; ?><a class="btn btn-outline" href="<?= nx21_url('hasil.php') ?>">Lihat semua hasil →</a></article><?php endif; endforeach; endif; ?></div></section>
<section class="section section-alt"><div class="container cards-4"><a class="feature-card" href="<?= nx21_url('timeline.php') ?>"><span>01</span><h3>Timeline</h3><p>Perjalanan angkatan dari awal hingga sekarang.</p></a><a class="feature-card" href="<?= nx21_url('galeri.php') ?>"><span>02</span><h3>Galeri</h3><p>Potongan momen dalam gambar.</p></a><a class="feature-card" href="<?= nx21_url('kelas.php') ?>"><span>03</span><h3>Kelas</h3><p>Pilih kelas dan lihat anggota di dalamnya.</p></a><a class="feature-card" href="<?= nx21_url('polling.php') ?>"><span>04</span><h3>Polling</h3><p>Masuk ke sistem voting resmi angkatan.</p></a></div></section>
<?php include __DIR__.'/includes/footer.php'; ?>
